# Presidential County Data

While other countries are okay, I wanted to get some US Presidential Data!! Here's some data from [Kaggle.com](https://www.kaggle.com/datasets/unanimad/us-election-2020?resource=download&select=president_county_candidate.csv)

In [2]:
import numpy as np
import plotly.express as px
import seaborn as sns
import pandas as pd

In [4]:
presData= pd.read_csv('president_county_candidate.csv')
presData.head(10)

      state             county      candidate party  total_votes    won
0  Delaware        Kent County      Joe Biden   DEM        44552   True
1  Delaware        Kent County   Donald Trump   REP        41009  False
2  Delaware        Kent County   Jo Jorgensen   LIB         1044  False
3  Delaware        Kent County  Howie Hawkins   GRN          420  False
4  Delaware  New Castle County      Joe Biden   DEM       195034   True
5  Delaware  New Castle County   Donald Trump   REP        88364  False
6  Delaware  New Castle County   Jo Jorgensen   LIB         2953  False
7  Delaware  New Castle County  Howie Hawkins   GRN         1282  False
8  Delaware      Sussex County   Donald Trump   REP        71230   True
9  Delaware      Sussex County      Joe Biden   DEM        56682  False

### Data Sets from Seaborn

We have also seen other built in datasets from Seaborn. Here are some of them that you might also find helpful.

To load seaborn, you'll need to run `import seaborn as sns`

1. **Titanic Dataset:**
> Contains data on passengers aboard the Titanic, including information on their survival status, age, sex, class, fare, and more.
> 
> `titanic_df = sns.load_dataset('titanic')`

2. **Functional Magnetic Resonance Imagine (fMRI) FMRI Dataset:**
> Contains functional magnetic resonance imaging (fMRI) data, with time series measurements taken at different points in the brain.
> 
> `fmri_df = sns.load_dataset('fmri')`

3. **Diamonds Dataset:**
> Contains data on diamonds, including their carat weight, cut, color, clarity, and price.
> 
> `diamonds_df = sns.load_dataset('diamonds')`

4. **Exercise Dataset:**
> Contains data from an exercise physiology study, including measurements such as subject IDs, age, weight, and the amount of exercise they performed.
> 
> `exercise_df = sns.load_dataset('exercise')`

In [5]:
titanic_df = sns.load_dataset('titanic')

fmri_df = sns.load_dataset('fmri')

diamonds_df = sns.load_dataset('diamonds')

exercise_df = sns.load_dataset('exercise')

In [6]:
exercise_df.head(10)

   Unnamed: 0  id     diet  pulse    time  kind
0           0   1  low fat     85   1 min  rest
1           1   1  low fat     85  15 min  rest
2           2   1  low fat     88  30 min  rest
3           3   2  low fat     90   1 min  rest
4           4   2  low fat     92  15 min  rest
5           5   2  low fat     93  30 min  rest
6           6   3  low fat     97   1 min  rest
7           7   3  low fat     97  15 min  rest
8           8   3  low fat     94  30 min  rest
9           9   4  low fat     80   1 min  rest